### ISSUE TITLE
Sessiones con multiples peticiones en espera

### ISSUE THREAD

**Issue by hlavrencic** [PunteriaCero/ElsaWorkflowDemo#5]

**Comment by rub2012** [comment]
para ejecutar mas de 1 mismo WF que estan esperando un llamado HTTP en la misma actividad:
ejemplo
workflows/test2_paso1?s1=tantos&s2=99&workflowInstanceId=9286eb9013f243e9

**Comment by hlavrencic** [comment]
Juli, armate un caso de ejemplo en la app porfa. Y exportate ese workflow en un archivo. Ese archivo lo podes adjuntar a este ticket. Y dejar las capturas acá a modo guía.

**Comment by rub2012** [comment]
1º Definir un WF y guardarlo, para iniciarlo hacer click en triangulo verde
<img width="956" alt="wf1" src="https://github.com/PunteriaCero/ElsaWorkflowDemo/assets/17799367/bffdfe8e-5329-4a2b-995e-eb03fda44a3b">
2º Al tener 2 instancias del mismo WF en ejecucion es necesario diferenciarlos al momento de invocarlos por endpoint
<img width="1898" alt="wf1_2" src="https://github.com/PunteriaCero/ElsaWorkflowDemo/assets/17799367/da66d7b6-831f-4ac2-9b6c-8ca737751701">
3º Se debe obtener el workflowInstanceId de la instancia que se desea ejecutar, que es el parametro ID en la columna derecha
<img width="1735" alt="wf1_3" src="https://github.com/PunteriaCero/ElsaWorkflowDemo/assets/17799367/a43e9aac-db5b-44ca-98f7-e3836c76dd22">
4º En postman se configura el path y el workflowInstanceId 
<img width="1612" alt="wf1_4" src="https://github.com/PunteriaCero/ElsaWorkflowDemo/assets/17799367/cd0ae872-8675-43e7-b32b-de57dc66c37c">
5º El wf indicado se ejecuta correctamente, el otro queda en espera
<img width="1715" alt="wf1_5" src="https://github.com/PunteriaCero/ElsaWorkflowDemo/assets/17799367/ceafcf21-c0dc-4452-a9c5-8e06427e4b78">

[test2.json](https://github.com/PunteriaCero/ElsaWorkflowDemo/files/14069088/test2.json)
